services:
  postgres:
    image: postgres:16-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  worker:
    build:
      context: .
      dockerfile: SWEN3.Sprint7/Dockerfile
    container_name: worker
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      CONNECTIONSTRINGS__PAPERLESSDB: ${CONNECTIONSTRINGS__PAPERLESSDB}

      BATCHFILESERVICE__INPUTFOLDERPATH: ${BATCHPROCESSING__INPUTFOLDERPATH}
      BATCHFILESERVICE__ARCHIVEFOLDERPATH: ${BATCHPROCESSING__ARCHIVEFOLDERPATH}
      BATCHFILESERVICE__ERRORFOLDERPATH: ${BATCHPROCESSING__ERRORFOLDERPATH}
      BATCHFILESERVICE__FILENAMEPATTERN: ${BATCHPROCESSING__FILENAMEPATTERN}
      BATCHFILESERVICE__CRONEXPRESSION: ${BATCHPROCESSING__CRONEXPRESSION}
      BATCHFILESERVICE__PROCESSONSTARTUP: ${BATCHPROCESSING__PROCESSONSTARTUP}
      BATCHFILESERVICE__TIMEZONE: ${BATCHPROCESSING__TIMEZONE}

      TZ: ${BATCHPROCESSING__TIMEZONE}

    volumes:
      - ./batch_data/input:/app/batch_input
      - ./batch_data/archive:/app/batch_archive
      - ./batch_data/error:/app/batch_error

volumes:
  pgdata:
