<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <UserSecretsId>dotnet-SWEN3.Sprint7-166745c0-98ad-4374-a8fb-00a2682f4bac</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0-rc.2.25454.107"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0-preview.7.25380.108" PrivateAssets="All"/>
        <PackageReference Include="TickerQ" Version="2.5.3"/>
        <PackageReference Include="TickerQ.Dashboard" Version="2.5.3"/>
        <PackageReference Include="TickerQ.EntityFrameworkCore" Version="2.5.3"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>
</Project>
